title: "Live a good life."
baseurl: "" # Leave empty for GitHub Pages
url: "https://username.github.io"


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown